export const SET_STORE = 'SET_STORE'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_PRODUCT_TO_CHECKOUT = 'ADD_PRODUCT_TO_CHECKOUT'
export const ADD_QUANTITY_TO_PRODUCT_IN_CART = 'ADD_QUANTITY_TO_PRODUCT_IN_CART'
