//store
export const SET_STORE = 'SET_STORE'

//products
export const SET_PRODUCTS = 'SET_PRODUCTS'

//cart
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'

export const ADD_QUANTITY_TO_PRODUCT_IN_CART = 'ADD_QUANTITY_TO_PRODUCT_IN_CART'
